dict_1 = {
    0: {'id': "sgesi", "name": "研究生+工作党+自由职业", "condition_'id's": ["zisju"], },
    1: {'id': "blrxwq", "name": "目标专升本", "condition_'id's": ["bslnzn"], },
    2: {'id': "yeklc", "name": "目标中考", "condition_'id's": ["jfsle"]},
    3: {'id': "baijjz", "name": "无考试目标（自我提升+保持语感）", "condition_'id's": ["vmhua"], },
    4: {'id': "cwzei", "name": "听力-专升本用户", "condition_'id's": ["bslnzn"], },
    5: {'id': "otbqx", "name": "目标旅行英语", "condition_'id's": ["nbtoz"], },
    6: {'id': "gkyza", "name": "目标扩大听力词汇量", "condition_'id's": ["ftgrq"], },
    7: {'id': "salou", "name": "目标其他", "condition_'id's": ["qgpic"], },
    8: {'id': "bvfjmu", "name": "目标托业", "condition_'id's": ["buzrgc"], },
    9: {'id': "wnzun", "name": "目标专八", "condition_'id's": ["pcgyp"], },
    10: {'id': "iycfg", "name": "目标专四", "condition_'id's": ["hooui"], },
    11: {'id': "ucbyq", "name": "目标六级", "condition_'id's": ["bclhtz"], },
    12: {'id': "bruyrp", "name": "目标四级", "condition_'id's": ["xbxai"], },
    13: {'id': "lhkie", "name": "职场（非大会员）", "condition_'id's": ["bqqfpx", "bsjlni"], },
    14: {'id': "eqaps", "name": "目标四六级（非大会员）", "condition_'id's": ["ugjmp", "bsjlni"], },
    15: {'id': "bzdkl", "name": "听力-目标职场的非大会员用户", "condition_'id's": ["tsuqs", "bsjlni"], },
    16: {'id': "bcjfas", "name": "听力-目标四六级的非大会员用户", "condition_'id's": ["ugjmp", "bsjlni"], },
    17: {'id': "xxofl", "name": "目标考研（非大会员）", "condition_'id's": ["brfpia", "bsjlni"], },
    18: {'id': "jfsle", "name": "听力-目标考研的非大会员用户", "condition_'id's": ["brfpia", "bsjlni"], },
    19: {'id': "vmhua", "name": "职场英语", "condition_'id's": ["kdpkg", "bqqfpx"], },
    20: {'id': "bslnzn", "name": "畅读会员（非大会员）", "condition_'id's": ["exicx", "bsjlni"], },
    21: {'id': "nbtoz", "name": "大会员", "condition_'id's": ["fedhp"], },
    22: {'id': "ftgrq", "name": "听力-是大会员，不是听力小会员", "condition_'id's": ["rmnze", "fedhp"], },
    23: {'id': "qgpic", "name": "听力-是听力口语会员，非大会员", "condition_'id's": ["iqmbl", "bsjlni"], },
    24: {'id': "buzrgc", "name": "大学生", "condition_'id's": ["swcvz"], },
    25: {'id': "bqqfpx", "name": "未拥有哈利波特套装", "condition_'id's": ["bkpzex"], },
    26: {'id': "kdpkg", "name": "非大会员", "condition_'id's": ["bsjlni"], },
    27: {'id': "bkpzex", "name": "目标高考（非畅读会员）", "condition_'id's": ["brfpi", "nxrcs"], },
    28: {'id': "ytmwg", "name": "目标六级（非畅读会员）", "condition_'id's": ["bclhtz", "nxrcs"], },
    29: {'id': "balqtu", "name": "目标四级（非畅读会员）", "condition_'id's": ["xbxai", "nxrcs"], },
    30: {'id': "cafan", "name": "目标考研（非畅读会员）", "condition_'id's": ["brfpia", "nxrcs"], },
    31: {'id': "bsjlni", "name": "畅读会员（包括已过期）", "condition_'id's": ["ytmwg"], },
    32: {'id': "nxrcs", "name": "从未买过畅读会员", "condition_'id's": ["balqtu"], },
    33: {'id': "fedhp", "name": "非初高中生及以下", "condition_'id's": ["cafan"], },
    34: {'id': "rmnze", "name": "听力-非扇贝大会员", "condition_'id's": ["bsjlni"], },
    35: {'id': "bvvbxe", "name": "非畅读会员", "condition_'id's": ["nxrcs"], },
    36: {'id': "phena", "name": "畅读会员", "condition_'id's": ["exicx"], },
    37: {'id': "iqmbl", "name": "听力-非听力口语会员用户", "condition_'id's": ["rmnze"], },
    38: {'id': "tdrgx", "name": "听力-大学生&四六级", "condition_'id's": ["swcvz", "ugjmp"], },
    39: {'id': "bqydkq", "name": "听力-听力口语会员", "condition_'id's": ["iqmbl"], },
    40: {'id': "brfpi", "name": "目标专四专八", "condition_'id's": ["bqydkq"], },
    41: {'id': "bclhtz", "name": "目标托福", "condition_'id's": ["lcnsc"], },
    42: {'id': "xbxai", "name": "目标雅思", "condition_'id's": ["doqdz"], },
    43: {'id': "juuxc", "name": "目标高考", "condition_'id's": ["brfpi"], },
    44: {'id': "brfpia", "name": "工作党/自由职业", "condition_'id's": ["mnvdu"], },
    45: {'id': "mnvdu", "name": "目标四六级", "condition_'id's": ["ugjmp"], },
    46: {'id': "exicx", "name": "目标考研", "condition_'id's": ["brfpia"], },
    47: {'id': "burubg", "name": "阅读-畅读会员/大会员", "condition_'id's": ["exicx"], },
    48: {'id': "odihq", "name": "阅读-已付费用户", "condition_'id's": ["qvyrg"], },
    49: {'id': "giwnn", "name": "阅读-未付费老用户", "condition_'id's": ["odihq", "burubg"], },
        
    }

for one,two in dict_1.items():
    for three,four in two.items():
        print(three)