# pytest.ini是pytest的主配置文件，用于集中管理项目的测试配置，让你的测试行为更加一致和高效。把它放在项目根目录下，pytest就能自动识别并应用其中的设置。
[pytest]
# 所有pytest相关配置都写在这个section下面。
# 添加默认命令行参数，可以省去每次运行pytest时都输入一长串命令的麻烦。
; addopts = -s -v --strict-markers -durations=5
# -s:在测试输出中显示print语句的内容
#-v：输出更详细的测试信息
# --strict-markert：如果使用了未在markers中注册的标记，pytest会报错，有助于规范化标记的使用
# -durations：显示最慢的X个测试

# 测试发现配置：pytest有一套默认的测试文件、类和函数发现规则（例如：寻找test_*.py或*_test.py文件）。可以通过这些选项来自定义规则。
# 匹配check_开头和*.py结尾的文件
; python_files = check_*.py

# 匹配Check开头的类
; python_classes = Check*

#匹配a_test_开头的函数
; python_functions = a_test_*

# 指定测试路径：如果你的测试文件都集中在特定的文件夹，使用这个选项可以加速测试文件的查找过程
; testpaths = /second_study/
